groups:
  - symbol: [3, 4, 3, 2]
    slices:
      - root: [0.30, 0.03, 0.03, 0.03, 0.01]
        color: [0.9, 0.3, 0.3]
      - root: [1.00, 0.10, 0.10, 0.10, 0.02]
        color: [0.3, 0.3, 0.3]
        exclude:
          - [0, 1, 2]
    wires:
      - root: [0.50, 0.05, 0.05, 0.05, 0.01]
        color: [0.9, 0.9, 0.9]
        curve: true
